import profile from "./assets/profile.jpeg";

export const personalData = {
  name: "Abuzar Yaseen",
  designation: ["Frontend Developer"],
  github: "https://github.com/AbuzarYaseen",
  linkedIn: "https://www.linkedin.com/in/abuzar-yaseen/",
  facebook: "https://www.facebook.com/abuzar.yaseen.3",
  instagram: "https://www.instagram.com/abuzaryaseen88/",
  skills: [
    "HTML",
    "CSS",
    "Javascript",
    "ReactJs",
    "NextJs",
    "GROQ",
    "Sanity",
    "Tailwind css",
    "Git",
    "GSAP Animations",
    "Bootstrap",
    "Material UI",
    "Ant Design",
    "shadcn/ui",
    "TypeScript",
    "Redux Toolkit",
    "Redux",
    "REST API",
    "Firebase",
    "Netlify",
    "Vercel",
    "Chakra UI",
    "Styled Components",
    "SASS",
  ],
  email: "abuzaryaseen88@gmail.com",
  phone: "+923054664830",
  address: "Lahore, Pakistan",
};

export const AboutData = {
  name: "Abuzar Yaseen",
  description:
    "I have over 1 year of experience in web, and custom software development using technologies such as NextJs, ReactJs, Tailwind css, Javascript, NodeJs, and various DBMS. I have worked across industries including real estate, e-commerce, and more.",
  profile: profile,
};

export const experiences = [
  {
    id: 1,
    title: "Frontend Software Engineer",
    company: "Cyber Evangelists",
    duration: "(Sep 15, 2024 - Present)",
    location: "Lahore, Pakistan",
    responsibilities: [
      "Frontend development with ReactJs, NextJs Framework, Tailwind, and AntD",
      "Performance and optimization of live products",
      "Provide optimal solutions",
    ],
  },
  {
    id: 2,
    title: "React Developer",
    company: "Codistal",
    duration: "(Feb 1,2024 - Jul 1, 2024)",
    location: "Lahore, Pakistan",
    responsibilities: [
      "Frontend development with ReactJs, and Tailwind",
      "Performance and optimization of live products",
      "Provide optimal solutions",
    ],
  },
  {
    id: 3,
    title: "React Developer Intern",
    company: "Zeikh Technologies",
    duration: "(Nov 2023 - Jan 2024)",
    location: "Lahore, Pakistan",
    responsibilities: [
      "Backend development with SFRA architecture",
      "Provide optimal solutions",
      "Performance and optimization of live products",
    ],
  },
];

export const skillsData = [
  // "Photoshop",
  // "Angular",
  "Next Js",
  // "Nuxt Js",
  "Typescript",
  // "Vue",
  // "Postgresql",
  "Tailwind",
  "ViteJs",
  "Vuetifyjs",
  // "C",
  "C++",
  "Dart",
  "Firebase",
  "MaterialUI",
  "Figma",
  "Flutter",
  // "Flask",
  "MySQL",
  "ReactJs",
  "Bootstrap",
  // "Docker",
  // "NodeJs",
  "SAAS",
  // "MongoDB",
  "HTML",
  "CSS",
  "Javascript",
  "Git",
  "GCP",
  "office",
  // "c#",
  // "illustrator",
  // "ionic",
  // "Python",
  // "Django",
  // "Django Rest Framework",
  // "RestAPI",
  // "Elixir",
  // "Phoenix",
  // "PostgreSQL",
  // "AWS",
  // "React Native",
  // "PHP",
  // "Laravel",
  // "DataScience",
  // "FastAPI",
  // "redis",
  // "graphql",
  // "microservices",
  // "jenkins",
  // "ionic",
];

export const educations = [
  {
    id: 1,
    title: "Bachelors in Computer Science",
    duration: "2019 - 2023",
    institution: "University of Engineering and Technology, Lahore",
  },
];

export const ContactMe = {
  description:
    "If you have any questions or concerns, please don't hesitate to contact me. I am open to any work opportunities that align with my skills and interests.",
};
